### PR TITLE
DDCE-5462: Update play-frontend-hmrc to 10.1.0

### PR DESCRIPTION
**Pull request by EdCope**
- Update play-frontend-hmrc from version `8.5.0` -> `10.1.0`
- Change from deprecated `HmrcLayout` to `HmrcStandardPage`
- Remove components which should be sourced from play-frontend-hmrc library

> - InsetPara -> GovukInsetText ([link](https://github.com/hmrc/advance-valuation-rulings-frontend/assets/87376121/4c3f97c8-d8e2-4310-a963-52e0f1f2ce8e))
> - DetailsDrop -> _wasn't used would be GovukDetails_
> - Warning -> GovukWarningText ([link](https://github.com/hmrc/advance-valuation-rulings-frontend/assets/87376121/a74af964-befb-4e50-b7b5-3111799a5e3c))

**Otherwise, visually looks the same aside from `GovukTag` on [AccountHomeView](https://github.com/hmrc/advance-valuation-rulings-frontend/assets/87376121/0ad70938-aab8-4848-b977-897769b9f9b0) and in `StandardBetaBanner` component throughout**

### CODE REVIEW

**Comment by lmugnai** [comment]
@EdCope can we try and update the following?
[info]   uk.gov.hmrc.mongo:hmrc-mongo-play-30                : 1.9.0 -> 2.0.0
[info]   uk.gov.hmrc.mongo:hmrc-mongo-test-play-30:test      : 1.9.0 -> 2.0.0
[info]   uk.gov.hmrc.objectstore:object-store-client-play-30 : 1.4.0 -> 2.0.0

**Comment by lmugnai** [comment]
@EdCope can we see if sbt-concat can be removed and cleanup up. I can see it's not enabled via lazy val root = (project in file(".")).enablePlugins(SbtWeb) and it's seems to be only concatenating 1 js file "app.js" -> application.js. Not entirely sure if it's being used elsewhere though.

**Comment by lmugnai** [comment]
@EdCope can we remove "The service also depends on mongodb." from readme?

**Comment by EdCope** [comment]
> @EdCope can we try and update the following?
> [info] uk.gov.hmrc.mongo:hmrc-mongo-play-30 : 1.9.0 -> 2.0.0
> [info] uk.gov.hmrc.mongo:hmrc-mongo-test-play-30:test : 1.9.0 -> 2.0.0
> [info] uk.gov.hmrc.objectstore:object-store-client-play-30 : 1.4.0 -> 2.0.0

Left these as they were the Scala 3 builds and when asking before thought we said just to do the update for `play-frontend-hmrc`. Happy to progress though as changes in them look fairly small. [hmrc-mongo](https://github.com/hmrc/hmrc-mongo/pull/122/files) &
[object-store-client](https://github.com/hmrc/object-store-client/pull/64/files). There is also `bootstrap-frontend` and `internal-auth-client` too which could go forward

> @EdCope can we see if sbt-concat can be removed and cleanup up. I can see it's not enabled via lazy val root = (project in file(".")).enablePlugins(SbtWeb) and it's seems to be only concatenating 1 js file "app.js" -> application.js. Not entirely sure if it's being used elsewhere though.

Looked a bit into this, pretty sure SbtWeb gets enabled by default with PlayScala plugin. When trying to remove it does introduce console errors in chrome to do with javascript, and there is some code to do with the autocomplete for example in the custom js. I think until we can definitely remove `app.js` file it should probably remain, had to leave it in for another repository for a couple of the methods it provides before too.

**Review by lmugnai — APPROVED** [review]

**Pull request merged**
